import "./globals.css";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "@/components/ui/sonner";
import { dark } from "@clerk/themes";
import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/chat/sidebar";
import { Header } from "@/components/chat/header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider appearance={{ baseTheme: dark }}>
      <SidebarProvider
        style={
          {
            "--sidebar-width": "19rem",
          } as React.CSSProperties
        }
      >
        <html lang="en" className="dark">
          <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased `}
          >
            <AppSidebar />
            <SidebarInset>
              <Header />
              <div className="bg-background flex h-dvh w-full overflow-hidden">
                <main className="@container relative h-dvh w-0 flex-shrink flex-grow overflow-y-auto">
                  {children}
                  <Toaster />
                </main>
              </div>
            </SidebarInset>
          </body>
        </html>
      </SidebarProvider>
    </ClerkProvider>
  );
}
